// Shared payment-method constants for the investment payment page.

export const MFS_PROVIDERS = ["Bikash", "Nagad", "Rocket", "Upay"];

// Scheduled banks of Bangladesh (state-owned, specialised, private & foreign).
export const BD_BANKS = [
  "Sonali Bank PLC",
  "Janata Bank PLC",
  "Agrani Bank PLC",
  "Rupali Bank PLC",
  "BASIC Bank Limited",
  "Bangladesh Development Bank PLC",
  "Bangladesh Krishi Bank",
  "Rajshahi Krishi Unnayan Bank",
  "Probashi Kallyan Bank",
  "AB Bank PLC",
  "Bank Asia PLC",
  "BRAC Bank PLC",
  "City Bank PLC",
  "Dhaka Bank PLC",
  "Dutch-Bangla Bank PLC",
  "Eastern Bank PLC",
  "IFIC Bank PLC",
  "Jamuna Bank PLC",
  "Meghna Bank PLC",
  "Mercantile Bank PLC",
  "Midland Bank PLC",
  "Modhumoti Bank PLC",
  "Mutual Trust Bank PLC",
  "National Bank Limited",
  "NCC Bank PLC",
  "NRB Bank PLC",
  "NRBC Bank PLC",
  "One Bank PLC",
  "Padma Bank PLC",
  "Premier Bank PLC",
  "Prime Bank PLC",
  "Pubali Bank PLC",
  "Southeast Bank PLC",
  "South Bangla Agriculture and Commerce Bank PLC",
  "Standard Bank PLC",
  "Trust Bank PLC",
  "United Commercial Bank PLC",
  "Uttara Bank PLC",
  "Bengal Commercial Bank PLC",
  "Citizens Bank PLC",
  // ── Islami / Shariah-based ──
  "Islami Bank Bangladesh PLC",
  "Al-Arafah Islami Bank PLC",
  "Social Islami Bank PLC",
  "EXIM Bank PLC",
  "First Security Islami Bank PLC",
  "ICB Islamic Bank Limited",
  "Shahjalal Islami Bank PLC",
  "Union Bank PLC",
  "Standard Chartered Bank",
  "HSBC Bangladesh",
  "Citibank N.A.",
  "Woori Bank",
  "Commercial Bank of Ceylon PLC",
  "State Bank of India",
  "Habib Bank Limited",
  "National Bank of Pakistan",
  "Bank Al-Falah Limited",
];
